### ISSUE TITLE
options -P --pid does not work

### ISSUE THREAD

**Issue by andrus7k** [josegonzalez/python-beaver#244]
-P /run/beaver.pid
--pid /run/beaver.pid

does not work
couldn't find any usage in code.

**Comment by JamieCressey** [comment]
-P and --pid appear to be working in the latest release. Please re-open if you're still having problems.

**Comment by ScottBrenner** [comment]
Any updates here? Not working in 36.2.1:

Running with
`$beaver ... -P /run/beaver.pid`

but
```
$ cat /run/beaver.pid
cat: /run/beaver.pid: No such file or directory
```

**Comment by josegonzalez** [comment]
@ScottBrenner please file a new issue, rather than comment on a 3+ year old issue.
