### ISSUE TITLE
How to ignore log lines that do not match regex

### ISSUE THREAD

**Issue by KingdomOfJoy** [josegonzalez/python-beaver#261]
Hello,

Is there a way for beaver to ignore certain log lines by checking whether it matches(or doesn't) match regex pattern. If there isn't, could you point me to a place in code where I can implement it.

Thank you!

**Comment by philbert** [comment]
hi,
im interested in this feature too. for example i just want to ship only apache logs with http codes 400 and 500.

**Comment by josegonzalez** [comment]
This feature is not implemented, feel free to open a PR adding this.
