### ISSUE TITLE
Low rate of sending to RabbitMQ

### ISSUE THREAD

**Issue by zhenghao1** [josegonzalez/python-beaver#265]
Has anyone used Beaver with RabbitMQ before?  I'm encountering only 300+ messages per second with RabbitMQ default config settings running only on one machine.  I never had an issue with Redis.  Redis was 3.5K messages per second.

**Comment by tspicer** [comment]
As mentioned by zhenghao1, the answer is in the connection details.

Within rabbitmq_transport.py (https://github.com/josegonzalez/python-beaver/blob/master/beaver/transports/rabbitmq_transport.py)

on line 49...
 "pika.adapters.BlockingConnection(parameters)"

to something like this

"pika.SelectConnection(parameters=parameters,
on_open_callback=on_open)"

Once I'm back at the office I will mess around and see if I can get it to work

**Comment by JamieCressey** [comment]
@tspicer did you manage to dig any further into this?
