### ISSUE TITLE
Ubuntu 14: ImportError during install

### ISSUE THREAD

**Issue by vigoatrook** [josegonzalez/python-beaver#285]
Please let me know if more details are needed.

OS: Ubuntu 14.04
Python version: 2.7.6
pip version: 1.5.4 (also tried 6.0.6)

Problem: Tried installing through *pip install Beaver* and downloading source then *python setup.py install* directly. Ended up gettting the same error message.

Error message given by `pip`:
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/redis
Storing debug log for failure in /root/.pip/pip.log

Error message from `Python`:

Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "/tmp/pip_build_root/redis/setup.py", line 59, in <module>
    'Programming Language :: Python :: 3.4',
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "<string>", line 12, in replacement_run
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
ImportError: No module named version

**Comment by josegonzalez** [comment]
Sounds like a redis bug? What version of redis is being installed?

Maybe makes sense to open this upstream, and not here, since I don't maintain the redis library.

**Comment by vigoatrook** [comment]
Thanks for replying quickly! I will re-submit this issue at the right place, but before this issue is closed here, have you had anyone submit a similar issue?

**Comment by josegonzalez** [comment]
Not that I can remember to be honest. I also normally build a debian package via dh-virtualenv (all the files are already in place) and install that way.

**Comment by vigoatrook** [comment]
Okay. I will likely explore the virtualenv option. Thanks again for helping!
