### ISSUE TITLE
Fails to install when using pip currently

### ISSUE THREAD

**Issue by wingZero21** [josegonzalez/python-beaver#289]
Hi,

Attempting to install this via pip however getting the below failure when installing currently.

Details:
```
Running setup.py egg_info for package python-daemon
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/tmp/pip-build-root/python-daemon/setup.py", line 26, in <module>
        import version
      File "version.py", line 435
        for item in versions}
          ^
    SyntaxError: invalid syntax
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/tmp/pip-build-root/python-daemon/setup.py", line 26, in <module>

    import version

  File "version.py", line 435

    for item in versions}

      ^

SyntaxError: invalid syntax

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-root/python-daemon
Storing complete log in /root/.pip/pip.log
```

**Comment by josegonzalez** [comment]
Yeah, known issue, I'll get to releasing a version today in a bit.

**Comment by aavileli** [comment]
is there an update on this issue

**Comment by blysik** [comment]
Any update?

**Comment by josegonzalez** [comment]
https://github.com/josegonzalez/python-beaver/releases/tag/33.1.0

Sorry about that!

**Comment by blysik** [comment]
Still errors for me:

Error: Execution of '/usr/bin/pip-python install -q git+git://github.com/josegonzalez/beaver.git@33.1.0#egg=Beaver' returned 1: Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-root/python-daemon
Storing complete log in /root/.pip/pip.log

Here's the big in the log:

Downloading/unpacking python-daemon>=1.5.2 (from Beaver)
  Running setup.py egg_info for package python-daemon
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/tmp/pip-build-root/python-daemon/setup.py", line 26, in <module>
        import version
      File "version.py", line 438
        for item in versions}
          ^
    SyntaxError: invalid syntax

This is OEL6.4.

**Comment by josegonzalez** [comment]
What python version are you running?

**Comment by blysik** [comment]
Python 2.6.6 (r266:84292, Dec 20 2012, 15:53:42)
