### ISSUE TITLE
HTTP Transport Not Reading In Existing JSON

### ISSUE THREAD

**Issue by c08d555e** [josegonzalez/python-beaver#294]
HTTP Transport works really well, except only if it's following a file.  It doesn't seem to behave the same way the other transports do, by which I mean it will not read in the contents of an existing JSON file and send that, it only sends new lines that are appended.  This works great for following, but if it crashes and needs to catch up it doesn't seem to be able to.  With logstash, it goes back and reads in the whole JSON file and sends it all.

Thoughts?  If this is not intentional, is there a way I can implement this?

**Comment by astral303** [comment]
This is the intended behavior by beaver, by default it starts streaming only new lines. To allow resume, you have to use the "Since DB" configuration option.
