### ISSUE TITLE
./beaver/tests/test_glob_sections.py file references a missing tests/square_bracket_sections.ini

### ISSUE THREAD

**Issue by jrwren** [josegonzalez/python-beaver#309]
./beaver/tests/test_glob_sections.py file references a missing tests/square_bracket_sections.ini

tests to not pass.

**Comment by josegonzalez** [comment]
https://github.com/josegonzalez/python-beaver/blob/master/tests/square_bracket_sections.ini

File is here.

**Comment by jrwren** [comment]
Thanks, that was the fastest reply ever.
