### ISSUE TITLE
Daemonize does not return

### ISSUE THREAD

**Issue by spg** [josegonzalez/python-beaver#318]
When I run from my terminal

```
beaver -c beaver.conf -t redis -P /tmp/beaver.pid -D
```

beaver does not return (it blocks). I would have expected the `-D` switch to make beaver return immediately and run in background.

Am I getting it right?

**Comment by spg** [comment]
Note that I am running in the context of a Docker container

**Comment by josegonzalez** [comment]
Seems to work here. Maybe something to do with the docker container?

**Comment by spg** [comment]
I think so, the only way I managed to run it was by forking it from my bash script with `&`:

```
beaver -c beaver.conf -t redis -P /tmp/beaver.pid -D &
```

**Comment by josegonzalez** [comment]
Going to say its docker related, unfortunately. Not sure why it wouldn't fork...

Feel free to update this issue with any other comments. Closing for now.
