### ISSUE TITLE
Main Consumer Queue is full?

### ISSUE THREAD

**Issue by jnicoleoliveira** [josegonzalez/python-beaver#331]
I am a new user to beaver. I am shipping my logs to a remote redis-server using ssh tunneling.

I had beaver running overnight, and came to find this error in the beaver log, and a stop to logs shipping. There doesn't seem to be an issue on the redis side, I'm not sure how this could be happening to beaver..

[2015-08-06 11:05:23,810] INFO    Starting queue consumer
[2015-08-06 11:05:23,833] ERROR   Main consumer queue is full
Process Process-1:7968:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/multiprocessing/process.py", line 232, in _bootstrap
    self.run()
  File "/usr/lib64/python2.6/multiprocessing/process.py", line 88, in run
    self._target(*self._args, **self._kwargs)
  File "/root/.local/lib/python2.6/site-packages/Beaver-34.0.0-py2.6.egg/beaver/run_queue.py", line 56, in run_queue
    if command == 'callback':
UnboundLocalError: local variable 'command' referenced before assignment
[2015-08-06 11:05:28,817] INFO    Starting queue consumer
[2015-08-06 11:05:28,835] ERROR   Main consumer queue is full
Process Process-1:7969:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/multiprocessing/process.py", line 232, in _bootstrap
    self.run()
  File "/usr/lib64/python2.6/multiprocessing/process.py", line 88, in run
    self._target(*self._args, **self._kwargs)
  File "/root/.local/lib/python2.6/site-packages/Beaver-34.0.0-py2.6.egg/beaver/run_queue.py", line 56, in run_queue
    if command == 'callback':
UnboundLocalError: local variable 'command' referenced before assignment

**Comment by josegonzalez** [comment]
Looks like [this pr](https://github.com/josegonzalez/python-beaver/commit/d159ec579c01b8fab532b3814c64b0ff8b2063ff) broke it. Feck. I can take a look tonight.

**Comment by josegonzalez** [comment]
Can you try out master and see if the issue is fixed?

**Comment by jnicoleoliveira** [comment]
Awesome, thank you. I'm just reinstalled... The error didn't occur until I had run the service for a while, so I will check it in about an hour or so to see if it happens again.
I am still receiving this part of the error however, 

 File "/usr/lib64/python2.6/multiprocessing/process.py", line 232, in _bootstrap
    self.run()
  File "/usr/lib64/python2.6/multiprocessing/process.py", line 88, in run
    self._target(*self._args, **self._kwargs)
  File "/root/.local/lib/python2.6/site-packages/Beaver-34.0.0-py2.6.egg/beaver/run_queue.py", line 56, in run_queue
    if command == 'callback':

**Comment by josegonzalez** [comment]
Please retest with latest master. Line 56 doesn't have that `command == 'callback'` line, so not sure what you are running...

**Comment by jnicoleoliveira** [comment]
Yes, I have installed the latest master. The error did not occur again during service start up, seems to be working fine. I will check again in a bit to confirm. Thank you.

**Comment by jnicoleoliveira** [comment]
I woke up this morning, and check on the daemon.. am still receiving the error..

[2015-08-07 09:51:34,109] ERROR   Main consumer queue is full
Process Process-1:7082:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/multiprocessing/process.py", line 232, in _bootstrap
    self.run()
  File "/usr/lib64/python2.6/multiprocessing/process.py", line 88, in run
    self._target(*self._args, **self._kwargs)
  File "/root/.local/lib/python2.6/site-packages/Beaver-34.0.0-py2.6.egg/beaver/run_queue.py", line 56, in run_queue
    if command == 'callback':
UnboundLocalError: local variable 'command' referenced before assignment

My processes are showing the [beaver]<defunct> again as well....
Not sure at all how this is being caused.

**Comment by josegonzalez** [comment]
Can you cat that `run_queue.py` file and gist the contents for me?

**Comment by jnicoleoliveira** [comment]
Yes.

# -*- coding: utf-8 -*-
import Queue
import signal
import sys
import time

from beaver.transports import create_transport
from beaver.transports.exception import TransportException
from unicode_dammit import unicode_dammit


def run_queue(queue, beaver_config, logger=None):
    signal.signal(signal.SIGTERM, signal.SIG_DFL)
    signal.signal(signal.SIGINT, signal.SIG_DFL)
    signal.signal(signal.SIGQUIT, signal.SIG_DFL)

    last_update_time = int(time.time())
    queue_timeout = beaver_config.get('queue_timeout')
    wait_timeout = beaver_config.get('wait_timeout')
    count = 0

    transport = None
    try:
        logger.debug('Logging using the {0} transport'.format(beaver_config.get('transport')))
        transport = create_transport(beaver_config, logger=logger)

        failure_count = 0
        while True:
            if not transport.valid():
                logger.info('Transport connection issues, stopping queue')
                break

            if int(time.time()) - last_update_time > queue_timeout:
                logger.info('Main consumer queue timeout of "{0}" seconds exceeded, stopping queue'.format(queue_timeout))
                break

            try:
                if queue.full():
                    logger.error("Main consumer queue is full")

                else:
                    if count == 1000:
                        logger.debug("Main consumer queue Size is: " + str(queue.qsize()))
                        count = 0
                    command, data = queue.get(block=True, timeout=wait_timeout)
                    if command == "callback":
                        last_update_time = int(time.time())
                        logger.debug('Last update time now {0}'.format(last_update_time))
            except Queue.Empty:
                if not queue.empty():
                    logger.error('Recieved timeout from main consumer queue - stopping queue')
                    break
                else:
                    logger.debug('No data')

            if command == 'callback':
                if data.get('ignore_empty', False):
                    logger.debug('removing empty lines')
                    lines = data['lines']
                    new_lines = []
                    for line in lines:
                        message = unicode_dammit(line)
                        if len(message) == 0:
                            continue
                        new_lines.append(message)
                    data['lines'] = new_lines

                if len(data['lines']) == 0:
                    logger.debug('0 active lines sent from worker')
                    continue

                while True:
                    try:
                        transport.callback(**data)
                        count += 1
                        break
                    except TransportException,e:
                        failure_count = failure_count + 1
                        if failure_count > beaver_config.get('max_failure'):
                            failure_count = beaver_config.get('max_failure')

                        sleep_time = beaver_config.get('respawn_delay') ** failure_count
                        logger.info('Caught transport exception, reconnecting in %d seconds' % sleep_time)
                        logger.debug(e)

                        try:
                            transport.invalidate()
                            time.sleep(sleep_time)
                            transport.reconnect()
                            if transport.valid():
                                failure_count = 0
                                logger.info('Reconnected successfully')
                        except KeyboardInterrupt:
                            logger.info('User cancelled respawn.')
                            transport.interrupt()
                            sys.exit(0)
            elif command == 'addglob':
                beaver_config.addglob(*data)
                transport.addglob(*data)
            elif command == 'exit':
                break
    except KeyboardInterrupt:
        logger.debug('Queue Interruped')
        if transport is not None:
            transport.interrupt()

        logger.debug('Queue Shutdown')

**Comment by josegonzalez** [comment]
How are you installing beaver?

**Comment by jnicoleoliveira** [comment]
I installed by downloading the tarball, building with the setup.py script, and installing via setup.py script.

**Comment by josegonzalez** [comment]
I don't think that worked - the file you pasted doesn't seem to reflect the latest version of beaver.

In any case, can you install the latest release? It should be `34.0.1` (I just released it a few minutes ago).

**Comment by jnicoleoliveira** [comment]
Ive installed the new version. lets see how it goes!

[]# beaver --version
Beaver 34.0.1

**Comment by jnicoleoliveira** [comment]
Its been running for nearly 20hrs now! I'm pretty sure its fixed.
 Thank you for your help!
