### ISSUE TITLE
Don't set "type: file" by default

### ISSUE THREAD

**Issue by eserte** [josegonzalez/python-beaver#334]
It's surprising that beaver sets the "type" field to "file" if it's not defined otherwise. And a default setting for this field means that it cannot be overwritten later in a (e.g) logstash redis input (because of https://www.elastic.co/guide/en/logstash/current/plugins-inputs-redis.html#plugins-inputs-redis-type : an existing type is not changed anymore).

Probably it's best to have no default value for the "type" field.

**Comment by josegonzalez** [comment]
What other type would it be? It's coming from a file, ergo `type => file`.

**Comment by eserte** [comment]
If you think of "type" as some kind of content-type, then you would be right. But logstash does not think so about "type". See for example https://www.elastic.co/guide/en/logstash/current/plugins-inputs-redis.html#plugins-inputs-redis-type : "Types are used mainly for filter activation." So it's more some kind of user-defined thing.

My suggestion is to not create the type field at all unless it's set in the configuration file.

**Comment by josegonzalez** [comment]
That definitely used to not be the case - in fact, I do recall having logstash-shipper add `type => file` itself for things coming in from a file input.

Allowing users to mangle this on their own is one thing - if you want to add that option, be my guest - but I'd rather not remove the default of `file`.

**Comment by eserte** [comment]
Well, if you want to keep the default of `file`, then this is your decision. But then you have to go through all the examples in https://github.com/josegonzalez/python-beaver/blob/master/docs/user/usage.rst setting `type` in the `input` block of the logstash config — this is unnecessary and misleading, it's always a no-op if using beaver. Either the user set `type` already in the beaver config, or the beaver's default kicked in.

**Comment by JamieCressey** [comment]
Closing this as it's a breaking change for little return and has had little traction over the past 4 months this issue has been open.
