### ISSUE TITLE
SNS transport too slow

### ISSUE THREAD

**Issue by JamieCressey** [josegonzalez/python-beaver#336]
Having tested the SNS transport method in production, the quantity of entries we processed proved too much for SNS to handle, resulting in "Queue is full" messages. (Which resulted in creating PR #335 instead).

Should the SNS transport be removed, or a warning placed in the docs?

**Comment by josegonzalez** [comment]
You mean your queue consumer is too slow (so not beaver). This sounds like operator error, and if you're using SNS, you should know how SNS works. 

Not removing or adding docs, since this is the fault of the user, not beaver.
