### ISSUE TITLE
redis_url with multi comma seperated redis servers

### ISSUE THREAD

**Issue by stavrosicsd** [josegonzalez/python-beaver#343]
If I set multiple redis servers in the beaver.conf (i.e. redis_url: redisA,redisB) do I have also load balancing on how the messages are sent? Or beaver client will just send messages to redisA and if it dies it will send the messages to redisB?

**Comment by JamieCressey** [comment]
The current logic is to roundrobin, trying the next server in the list upon failure. See:

https://github.com/josegonzalez/python-beaver/blob/f2afc85dab8c4307dddd81d52ac4cc97dd48caa1/beaver/transports/redis_transport.py#L114-L151
