### ISSUE TITLE
how to check logs sender host name. lets suppose my system receiving logs from multiple sources, how to differentiate them. beaver fetching the current hostname or either manually given name in conf file.

### ISSUE THREAD

**Issue by AS2015** [josegonzalez/python-beaver#349]

**Comment by josegonzalez** [comment]
Please read the documentation, this information is available there.

**Comment by AS2015** [comment]
here what i am doing, i am sending logs from my local machine to vm and then vm to another server. but when i receiving logs at vm and doing stdout to display them then beaver showing host name of vm irrespective of local machine. if i given host name manually in configuration file then it still remain same for all the other machine (host) that sending logs to vm.
