### ISSUE TITLE
beaver transport stopped after kafka cluster unavaiable on kafka-python 0.9.4

### ISSUE THREAD

**Issue by coregear** [josegonzalez/python-beaver#352]
on kafka-python 0.9.3
When some kafka partations not avaiable or restore to normal, beaver will print some error log and resore transport, it's OK.
but on kafka-python 0.9.4
transport will stopped at  kafka partations not avaiable even it's restore to normal, beaver is always stop transport data until do a restart. and during this period data was lost.
Please fix this on kafka-python 0.9.4, thanks!

**Comment by josegonzalez** [comment]
Sounds like maybe a kafka-python bug, not a dokku bug?

**Comment by coregear** [comment]
maybe, but not sure. could you help to review the code. thanks!
I noticed kafka_transport.py has no reconnect function, but other transports has this function.
