### ISSUE TITLE
Add support for the lumberjack protocol

### ISSUE THREAD

**Issue by josegonzalez** [josegonzalez/python-beaver#47]
This one might be a doozy, and I'll probably need @jordansissel to document the protocol.

**Comment by JamieCressey** [comment]
Closing as Lumberjack's EOL

**Comment by eht16** [comment]
For future maintainers, it might interesting I recently wrote a simple implementation of the Beats protocol (Lumberjack's successor): https://github.com/eht16/pylogbeat

The protocol implementation is probably not complete as it is still not documented completely.
But for basic usage it works and might be improved in the future.
